const hotels = [
  {
    id: 1,
    rating: 4,
    name: "Manhattan Hotel Jakarta",
    distance: "700m",
    price: "± IDR 1.200.000",
    url: "https://hotel-manhattan.com/?utm_source=GoogleMyBusiness&utm_medium=GoogleMyBusiness&utm_campaign=GoogleMyBusiness",
  },
  {
    id: 2,
    rating: 4,
    name: "Artotel Casa Kuningan",
    distance: "900m",
    price: "± IDR 1.000.000",
    url: "https://artotelwanderlust.com/hotel/artotel-casa-kuningan/g/Jakarta-ms.html?checkIn=2025-03-12&checkOut=2025-03-13&id=MA05110755-MA2311000003&encodeId=TUEyMzExMDAwMDAz",
  },
  {
    id: 3,
    rating: 5,
    name: "The Grove Suites by Grand Aston",
    distance: "1,1km",
    price: "± IDR 1.500.000",
    url: "https://www.astonhotelsinternational.com/en/hotel/view/44/the-grove-suites",
  },
  {
    id: 4,
    rating: 4,
    name: "Mercure Jakarta Gatot Subroto",
    distance: "1,2km",
    price: "± IDR 900.000",
    url: "https://all.accor.com/hotel/B151/index.en.shtml?utm_campaign=seo+maps&utm_medium=seo+maps&utm_source=google+Maps",
  },
  {
    id: 5,
    rating: 3,
    name: "Rasuna Icon Jakarta",
    distance: "1,3km",
    price: "± IDR 550.000",
    url: "https://www.rasunaiconjakarta.com/#2",
  },
  {
    id: 6,
    rating: 3,
    name: "favehotel Gatot Subroto",
    distance: "1,5km",
    price: "± IDR 500.000",
    url: "https://www.favehotels.com/en/hotel/view/6/favehotel-gatot-subroto",
  },
  {
    id: 7,
    rating: 5,
    name: "Gran Melia Jakarta",
    distance: "1,5km",
    price: "± IDR 2.200.000",
    url: "https://www.melia.com/en/hotels/indonesia/jakarta/gran-melia-jakarta?utm_campaign=google&utm_content=5711&utm_medium=organic&utm_source=directories",
  },
  {
    id: 8,
    rating: 4,
    name: "Fraser Place Setiabudi",
    distance: "1,5km",
    price: "± IDR 1.800.000",
    url: "https://www.frasershospitality.com/en/indonesia/jakarta/fraser-place-setiabudi-jakarta/?utm_source=google_map&utm_medium=organic",
  },
  {
    id: 9,
    rating: 3,
    name: "Amaris Hotel Satrio Kuningan",
    distance: "1,7km",
    price: "± IDR 400.000",
    url: "-",
  },
  {
    id: 10,
    rating: 5,
    name: "The Westin Jakarta",
    distance: "1,8km",
    price: "± IDR 3.000.000",
    url: "https://www.marriott.com/en-us/hotels/jktwi-the-westin-jakarta/overview/?scid=f2ae0541-1279-4f24-b197-a979c79310b0",
  },
  {
    id: 11,
    rating: 5,
    name: "The Ritz-Carlton Jakarta, Mega Kuningan",
    distance: "1,8km",
    price: "± IDR 3.000.000",
    url: "https://www.ritzcarlton.com/en/hotels/jktrz-the-ritz-carlton-jakarta-mega-kuningan/overview/?scid=f2ae0541-1279-4f24-b197-a979c79310b0",
  },
  {
    id: 12,
    rating: 4,
    name: "Ascott Kuningan Jakarta",
    distance: "1,8km",
    price: "± IDR 2.000.000",
    url: "https://www.discoverasr.com/en/ascott-the-residence/indonesia/ascott-kuningan-jakarta?utm_source=google&utm_medium=maps&utm_campaign=hq-google-gmb-alwayson-all-all-id-id-ascottkuninganjakarta-AKJ-gbp",
  },
];

export default hotels;
